language: ruby

before_install: gem install bundler --pre

bundler_args: --without development staging production

script:
  - RACK_ENV=test
  - xvfb-run bundle exec padrino rake

rvm:
  - 1.9.3-p547

branches:
  only:
    - master
    - develop

notifications:
  email:
    - dandanielw@gmail.com
    - damianlattenero@gmail.com
